### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by howlingengines** [lnstadrum/beatmup#16]
I'm having problems installing on windows 8.1 (AMD 8-4555,12GbRAM). The output is :-
C:\beatmup\build>cmake -DUSE_OPENGL=ON ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 6.3.9600.
CMake Error at pybind11/tools/FindPythonLibsNew.cmake:127 (message):
  Python config failure: Python is 64-bit, chosen compiler is 32-bit
Call Stack (most recent call first):
  pybind11/tools/pybind11Tools.cmake:16 (find_package)
  pybind11/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "C:/beatmup/build/CMakeFiles/CMakeOutput.log".
----------
I've tried several Python installations from Python 3.6.3(64bit) up to Python 3.7.9-32/64 installs , setting path each time.
when I try 'cmake --system-information' the relevant output shows :-
C:\beatmup\build>cmake --system-information | more | grep "python"
PYTHON_EXECUTABLE:FILEPATH=C:/Program Files/csiro.au/workspace/Python36/python.exe
FIND_PACKAGE_MESSAGE_DETAILS_PythonInterp:INTERNAL=[C:/Program Files/csiro.au/workspace/Python36/python.exe][v3.6.5()]

I assume I am doing something stupid!(as usual).
rgrds
JonH

**Comment by lnstadrum** [comment]
Hi @howlingengines,

It does not seem that you are doing something stupid, do not be that hard on yourself. :)

If you want to compile Beatmup, you need a C++ compiler installed. For example, Visual Studio Community Edition is free and does the job. From the log you posted I cannot identify whether you have it or not. Do you have Visual Studio or a different compiler?

On the other note, if you want to use Beatmup as is in Python without modifying its C++ source code, you can simply do `pip install beatmup` (should work with 64-bit).

lnstadrum

**Comment by howlingengines** [comment]
as usual me being  too hasty ( I've got too used to Linux!). by closing all cmd prompts , setting path via systemproperties->environment variables and recloning from git , all now works fine.
Many thanks Instadrum for your kind concern and I have to say , an excellent product.
Go Well.
