### ISSUE TITLE
Example Benchmarks

### ISSUE THREAD

**Issue by msx23** [lnstadrum/beatmup#18]
Hello,

first of all this project sounds very interesting, because it is the only framework (that I could find) that tries to enable neural network inferencing on OpenGL-ES2.0 devices, which includes a lot of low-power embedded Linux boards. I will take a look at the framework in the coming days or weeks when I have some time.

In the meantime, are there any benchmarks available as how the Open-GL-ES2.0 inference compares to a raw CPU inference with the same tensorflow model on any device? For me the interesting part would be to move some model parts to the GPU (even if it is a bit slower) in order to offload the CPU. But I have no idea how much slower a basic convolution model would be on GPU, is there any information available (no matter on what exact hardware or what exact model, just as a rough estimate)?

**Comment by lnstadrum** [comment]
Hi @msx23,

Thank you for your interest to Beatmup, and sorry for the delayed reply.

Unfortunately I do not have any comparative benchmarks with CPU, but I might have few relevant inputs to share.

The most elaborated work using Beatmup to run inference of a neural net is presented this article:
[https://lnstadrum.medium.com/towards-gpu-accelerated-image-classification-on-low-end-hardware-ec592e125ad9](https://lnstadrum.medium.com/towards-gpu-accelerated-image-classification-on-low-end-hardware-ec592e125ad9)
When I was implementing this, I tried to install TensorFlow to have such a comparison on Pi Zero W, but it failed to run even a basic convolution. I gave up on trying too soon without spending much effort...

Then, there are public benchmarks of MobileNets on Raspberry Pi, like this one:
[https://www.hackster.io/news/benchmarking-tensorflow-lite-on-the-new-raspberry-pi-4-model-b-3fd859d05b98](https://www.hackster.io/news/benchmarking-tensorflow-lite-on-the-new-raspberry-pi-4-model-b-3fd859d05b98)
From what presented there, it seems that Raspberry Pi 3 B+ is capable of running much bigger models (in terms of number of multiply-adds) like MobileNet v2 SSD, compared to the model in my article, in a rather similar time to what Beatmup achieves on GPU with this small model (e.g. 379.6 ms vs 328 ms respectively). This leaves quite a little hope for me that at least on Pi 3 B+ I can get something practical from GPU regardless the optimization effort I spent on the inference code. There are still quite a lot of differences between the two experiments (this comparison is very rough), and it would be nice to do a test using the same model and hardware. Unfortunately I do not have much bandwidth to do this in a near future.

Hope this helps!

lnstadrum
