### ISSUE TITLE
Segmentation fault when import tensorflow and beatmup

### ISSUE THREAD

**Issue by jenamax** [lnstadrum/beatmup#23]
Hello! I have a problem of usage beatmup with tensorflow. When I import one of those libraries everything is ok. But import of both of these modules gives a fault.

This code gives the error "Segmentation fault (core dumped)"
import tensorflow
import beatmup

And this code gives "Floating point exception (core dumped)"
import beatmup
import tensorflow

**Comment by lnstadrum** [comment]
Hello,

Thank you or your interest to Beatmup.

I confirm the issue with TF 2.11, but everything works as expected with TF 2.7. Will take a look.

**Comment by jenamax** [comment]
Yes, downgrading to tf 2.7 helped. Thanks!

**Comment by lnstadrum** [comment]
The problem seemingly comes from incompatible compilers between TensorFlow and Beatmup. For newer versions of TensorFlow you may need to recompile Beatmup on your own with GCC version up-to-date. The following worked for me:

```
Ubuntu 22.04
GCC/G++ 11.3.0
Python 3.10.6
TensorFlow 2.10.0
```

In a freshly started docker container with Ubuntu 22.04:
```
apt update
apt install -y cmake gcc g++ freeglut3-dev python3 python3-dev python3-pip
cmake -B build -DUSE_GLX=ON
cd build && make
python3 -m pip install tensorflow
python3 -c "import tensorflow; import beatmup; beatmup.say_hi()"
```
