### ISSUE TITLE
Code to train and GSLS conversion?

### ISSUE THREAD

**Issue by arianaa30** [lnstadrum/beatmup#31]
I'm very interested in the project. Is there a script to train a model on my own dataset and then convert the model to GLSL shader? I want to load the shader in Android.

**Comment by lnstadrum** [comment]
Hello,

If your question is related to the x2 super-resolution model, the original keras/TF code is available here:
https://gist.github.com/lnstadrum/0e2fec1e96bc6791f0ee3487969632ee

More details in the article:
https://medium.com/analytics-vidhya/inferring-a-super-resolution-neural-network-on-raspberry-pi-gpu-89b5456d21ef
