### ISSUE TITLE
Android code doesnt import in Android Studio

### ISSUE THREAD

**Issue by arianaa30** [lnstadrum/beatmup#32]
I was trying to import the Android project. But looks like it is an old project and there are issues with importing it. Can you make sure it can be imported with recent Android Studios and SDK changes?

`cvc-complex-type.2.4.a: Invalid content was found starting with element 'base-extension'. One of '{layoutlib}' is expected.
`...
//and other errors:
```
* Exception is:
	Caused by: groovy.lang.MissingMethodException: No signature of method: build_2nizcq2ad1zthut2lgnlna1fc.android() is applicable for argument types: (build_2nizcq2ad1zthut2lgnlna1fc$_run_closure1) values: [build_2nizcq2ad1zthut2lgnlna1fc$_run_closure1@7163f77b]
	at build_2nizcq2ad1zthut2lgnlna1fc.run
```

**Comment by lnstadrum** [comment]
Hello,

Thank you for your interest to Beatmup.

The Android project has been upgraded to a newer Gradle version, together with the associated dockerfile. GitHub Action building the android app is performed successfully on the master branch.
