### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by REDVM** [lnstadrum/beatmup#9]
Hello,
I would be interested in using Beatmup for prototyping personal projects and maybe in the future in a commercial product, but the GPL license almost forbids commercial use.
Do you plan on changing the license of Beatmup? Like a BSD license (PyTorch, Caffe, Theano), an Apache license (TensorFlow) or maybe MIT/LGPL?

Thank you very much!

**Comment by lnstadrum** [comment]
Hi Victor,

Thanks for your interest to Beatmup.
The license is quite restrictive indeed. You can consider purchasing a license exception for commercial use. If this is an option for you, feel free to reach out at beatmup.imaging@gmail.com

Thanks,
lnstadrum
